EyeSpy:
  database:
    host: "localhost"
    port: "3306"
    username: "root"
    password: ""
    database: "testing"
    prefix: "eyespy_"
  other:
    servername: "CraftBukkit"
    debug: "false"
    ignore: "[bot, otherbot]"